### PR TITLE
Ci test

### PR DESCRIPTION
**Pull request by aremazeilles**
These changes introduce:

 * A CI process (github action), in whish the docker image gets created,
 * A test of the docker image, according to a testing plan provided.

The testing is done through the CI process.

Please handle #8 before looking at this

### CODE REVIEW

**Comment by aremazeilles** [comment]
Just above this post, we see tje CI process, Clicking on it, we can see how it goes, and whether it succeeded or not. We should wait to see a green tick, meaning the CI process went well.

**Comment by aremazeilles** [comment]
Still have issue to solve. Cannot be merge anyhow until the CI process is succesful. Please wait...

**Comment by aremazeilles** [comment]
Now it is fine

**Review by jamatics — APPROVED** [review]
It looks OK to me.

**Comment by jamatics** [comment]
I am merging the pull request to master. It seems OK to me.

**Pull request merged**
