### PR TITLE
adjust CI process and apply linting

### PR DESCRIPTION
**Pull request by aremazeilles**
Update of the CI process

### CODE REVIEW

**Comment by aremazeilles** [comment]
It requires adjustment in questionnaire_lowAssist.csv, questionnaire_medAssist.csv, questionnaire_borgScale10_meta.csv, questionnaire_medAssist.csv, and adding a line in the scalar PI files.
You can see the changes through the Files Changed button above. 

Are these changes acceptable for you?

**Comment by aremazeilles** [comment]
ping

**Comment by jamatics** [comment]
Hi Anthony, 

These subjective questionnaire files are generated by our web application. I prefer to keep the previous file format [by keeping the ; at the end of each line] if it is ok with you. 
Thanks, 
Jawad

**Comment by aremazeilles** [comment]
I reinserted the extra `;` at the end of the csv files. Before merging this, I would still have other item to check on the master, so do not merge for the moment.

**Comment by aremazeilles** [comment]
Since the main changes are now limited to adjustment of CI files (and an addition of return character in the scalar store function), I will take the liberty to merge this, to handle more easily the next issue to handle

**Pull request merged**
